// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgNewClass } from "./types/cosmos/nft/v1beta1/tx";
import { MsgMintNFT } from "./types/cosmos/nft/v1beta1/tx";
import { MsgNftSend } from "./types/cosmos/nft/v1beta1/tx";

import { EventSend as typeEventSend} from "./types"
import { EventMint as typeEventMint} from "./types"
import { EventBurn as typeEventBurn} from "./types"
import { EventNewClass as typeEventNewClass} from "./types"
import { Entry as typeEntry} from "./types"
import { Class as typeClass} from "./types"
import { NFT as typeNFT} from "./types"
import { NftList as typeNftList} from "./types"

export { MsgNewClass, MsgMintNFT, MsgNftSend };

type sendMsgNewClassParams = {
  value: MsgNewClass,
  fee?: StdFee,
  memo?: string
};

type sendMsgMintNFTParams = {
  value: MsgMintNFT,
  fee?: StdFee,
  memo?: string
};

type sendMsgNftSendParams = {
  value: MsgNftSend,
  fee?: StdFee,
  memo?: string
};


type msgNewClassParams = {
  value: MsgNewClass,
};

type msgMintNFTParams = {
  value: MsgMintNFT,
};

type msgNftSendParams = {
  value: MsgNftSend,
};


export const registry = new Registry(msgTypes);

type Field = {
	name: string;
	type: unknown;
}
function getStructure(template) {
	const structure: {fields: Field[]} = { fields: [] }
	for (let [key, value] of Object.entries(template)) {
		let field = { name: key, type: typeof value }
		structure.fields.push(field)
	}
	return structure
}
const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgNewClass({ value, fee, memo }: sendMsgNewClassParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgNewClass: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgNewClass({ value: MsgNewClass.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgNewClass: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgMintNFT({ value, fee, memo }: sendMsgMintNFTParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgMintNFT: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgMintNFT({ value: MsgMintNFT.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgMintNFT: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgNftSend({ value, fee, memo }: sendMsgNftSendParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgNftSend: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgNftSend({ value: MsgNftSend.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgNftSend: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgNewClass({ value }: msgNewClassParams): EncodeObject {
			try {
				return { typeUrl: "/cosmos.nft.v1beta1.MsgNewClass", value: MsgNewClass.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgNewClass: Could not create message: ' + e.message)
			}
		},
		
		msgMintNFT({ value }: msgMintNFTParams): EncodeObject {
			try {
				return { typeUrl: "/cosmos.nft.v1beta1.MsgMintNFT", value: MsgMintNFT.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgMintNFT: Could not create message: ' + e.message)
			}
		},
		
		msgNftSend({ value }: msgNftSendParams): EncodeObject {
			try {
				return { typeUrl: "/cosmos.nft.v1beta1.MsgNftSend", value: MsgNftSend.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgNftSend: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	public structure: Record<string,unknown>;
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		this.structure =  {
						EventSend: getStructure(typeEventSend.fromPartial({})),
						EventMint: getStructure(typeEventMint.fromPartial({})),
						EventBurn: getStructure(typeEventBurn.fromPartial({})),
						EventNewClass: getStructure(typeEventNewClass.fromPartial({})),
						Entry: getStructure(typeEntry.fromPartial({})),
						Class: getStructure(typeClass.fromPartial({})),
						NFT: getStructure(typeNFT.fromPartial({})),
						NftList: getStructure(typeNftList.fromPartial({})),
						
		};
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			CosmosNftV1Beta1: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;