version: 1
accounts:
- name: alice
  coins:
  - 200000000umec
- name: bob
  coins:
  - 100000000umec
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 100000umec
validators:
- name: alice
  bonded: 100000000umec
