// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: mechain/mekyc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetRegionRequest struct {
	RegionId string `protobuf:"bytes,1,opt,name=regionId,proto3" json:"regionId,omitempty"`
}

func (m *QueryGetRegionRequest) Reset()         { *m = QueryGetRegionRequest{} }
func (m *QueryGetRegionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRegionRequest) ProtoMessage()    {}
func (*QueryGetRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{2}
}
func (m *QueryGetRegionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRegionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRegionRequest.Merge(m, src)
}
func (m *QueryGetRegionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRegionRequest proto.InternalMessageInfo

func (m *QueryGetRegionRequest) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

type QueryGetRegionResponse struct {
	Region Region `protobuf:"bytes,1,opt,name=region,proto3" json:"region"`
}

func (m *QueryGetRegionResponse) Reset()         { *m = QueryGetRegionResponse{} }
func (m *QueryGetRegionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRegionResponse) ProtoMessage()    {}
func (*QueryGetRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{3}
}
func (m *QueryGetRegionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRegionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRegionResponse.Merge(m, src)
}
func (m *QueryGetRegionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRegionResponse proto.InternalMessageInfo

func (m *QueryGetRegionResponse) GetRegion() Region {
	if m != nil {
		return m.Region
	}
	return Region{}
}

type QueryAllRegionRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegionRequest) Reset()         { *m = QueryAllRegionRequest{} }
func (m *QueryAllRegionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegionRequest) ProtoMessage()    {}
func (*QueryAllRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{4}
}
func (m *QueryAllRegionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegionRequest.Merge(m, src)
}
func (m *QueryAllRegionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegionRequest proto.InternalMessageInfo

func (m *QueryAllRegionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRegionResponse struct {
	Region     []Region            `protobuf:"bytes,1,rep,name=region,proto3" json:"region"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRegionResponse) Reset()         { *m = QueryAllRegionResponse{} }
func (m *QueryAllRegionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRegionResponse) ProtoMessage()    {}
func (*QueryAllRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{5}
}
func (m *QueryAllRegionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRegionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRegionResponse.Merge(m, src)
}
func (m *QueryAllRegionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRegionResponse proto.InternalMessageInfo

func (m *QueryAllRegionResponse) GetRegion() []Region {
	if m != nil {
		return m.Region
	}
	return nil
}

func (m *QueryAllRegionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetKycRequest struct {
	Account string `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
}

func (m *QueryGetKycRequest) Reset()         { *m = QueryGetKycRequest{} }
func (m *QueryGetKycRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetKycRequest) ProtoMessage()    {}
func (*QueryGetKycRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{6}
}
func (m *QueryGetKycRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKycRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKycRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKycRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKycRequest.Merge(m, src)
}
func (m *QueryGetKycRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKycRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKycRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKycRequest proto.InternalMessageInfo

func (m *QueryGetKycRequest) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

type QueryGetKycResponse struct {
	Kyc Kyc `protobuf:"bytes,1,opt,name=kyc,proto3" json:"kyc"`
}

func (m *QueryGetKycResponse) Reset()         { *m = QueryGetKycResponse{} }
func (m *QueryGetKycResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetKycResponse) ProtoMessage()    {}
func (*QueryGetKycResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{7}
}
func (m *QueryGetKycResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetKycResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetKycResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetKycResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetKycResponse.Merge(m, src)
}
func (m *QueryGetKycResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetKycResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetKycResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetKycResponse proto.InternalMessageInfo

func (m *QueryGetKycResponse) GetKyc() Kyc {
	if m != nil {
		return m.Kyc
	}
	return Kyc{}
}

type QueryAllKycRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKycRequest) Reset()         { *m = QueryAllKycRequest{} }
func (m *QueryAllKycRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllKycRequest) ProtoMessage()    {}
func (*QueryAllKycRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{8}
}
func (m *QueryAllKycRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKycRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKycRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKycRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKycRequest.Merge(m, src)
}
func (m *QueryAllKycRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKycRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKycRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKycRequest proto.InternalMessageInfo

func (m *QueryAllKycRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllKycResponse struct {
	Kyc        []Kyc               `protobuf:"bytes,1,rep,name=kyc,proto3" json:"kyc"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllKycResponse) Reset()         { *m = QueryAllKycResponse{} }
func (m *QueryAllKycResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllKycResponse) ProtoMessage()    {}
func (*QueryAllKycResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{9}
}
func (m *QueryAllKycResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllKycResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllKycResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllKycResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllKycResponse.Merge(m, src)
}
func (m *QueryAllKycResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllKycResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllKycResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllKycResponse proto.InternalMessageInfo

func (m *QueryAllKycResponse) GetKyc() []Kyc {
	if m != nil {
		return m.Kyc
	}
	return nil
}

func (m *QueryAllKycResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryKycByRegionRequest struct {
	RegionId string `protobuf:"bytes,1,opt,name=regionId,proto3" json:"regionId,omitempty"`
}

func (m *QueryKycByRegionRequest) Reset()         { *m = QueryKycByRegionRequest{} }
func (m *QueryKycByRegionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryKycByRegionRequest) ProtoMessage()    {}
func (*QueryKycByRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{10}
}
func (m *QueryKycByRegionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryKycByRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryKycByRegionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryKycByRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKycByRegionRequest.Merge(m, src)
}
func (m *QueryKycByRegionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryKycByRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKycByRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKycByRegionRequest proto.InternalMessageInfo

func (m *QueryKycByRegionRequest) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

type QueryKycByRegionResponse struct {
}

func (m *QueryKycByRegionResponse) Reset()         { *m = QueryKycByRegionResponse{} }
func (m *QueryKycByRegionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryKycByRegionResponse) ProtoMessage()    {}
func (*QueryKycByRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{11}
}
func (m *QueryKycByRegionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryKycByRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryKycByRegionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryKycByRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryKycByRegionResponse.Merge(m, src)
}
func (m *QueryKycByRegionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryKycByRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryKycByRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryKycByRegionResponse proto.InternalMessageInfo

type QueryFixedDepositByRegionRequest struct {
	RegionId   string             `protobuf:"bytes,1,opt,name=regionId,proto3" json:"regionId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryFixedDepositByRegionRequest) Reset()         { *m = QueryFixedDepositByRegionRequest{} }
func (m *QueryFixedDepositByRegionRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFixedDepositByRegionRequest) ProtoMessage()    {}
func (*QueryFixedDepositByRegionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{12}
}
func (m *QueryFixedDepositByRegionRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFixedDepositByRegionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFixedDepositByRegionRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFixedDepositByRegionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFixedDepositByRegionRequest.Merge(m, src)
}
func (m *QueryFixedDepositByRegionRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFixedDepositByRegionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFixedDepositByRegionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFixedDepositByRegionRequest proto.InternalMessageInfo

func (m *QueryFixedDepositByRegionRequest) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *QueryFixedDepositByRegionRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryFixedDepositByRegionResponse struct {
	Pagination *query.PageResponse `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryFixedDepositByRegionResponse) Reset()         { *m = QueryFixedDepositByRegionResponse{} }
func (m *QueryFixedDepositByRegionResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFixedDepositByRegionResponse) ProtoMessage()    {}
func (*QueryFixedDepositByRegionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fe7261689e004517, []int{13}
}
func (m *QueryFixedDepositByRegionResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFixedDepositByRegionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFixedDepositByRegionResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFixedDepositByRegionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFixedDepositByRegionResponse.Merge(m, src)
}
func (m *QueryFixedDepositByRegionResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFixedDepositByRegionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFixedDepositByRegionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFixedDepositByRegionResponse proto.InternalMessageInfo

func (m *QueryFixedDepositByRegionResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "mechain.mekyc.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "mechain.mekyc.QueryParamsResponse")
	proto.RegisterType((*QueryGetRegionRequest)(nil), "mechain.mekyc.QueryGetRegionRequest")
	proto.RegisterType((*QueryGetRegionResponse)(nil), "mechain.mekyc.QueryGetRegionResponse")
	proto.RegisterType((*QueryAllRegionRequest)(nil), "mechain.mekyc.QueryAllRegionRequest")
	proto.RegisterType((*QueryAllRegionResponse)(nil), "mechain.mekyc.QueryAllRegionResponse")
	proto.RegisterType((*QueryGetKycRequest)(nil), "mechain.mekyc.QueryGetKycRequest")
	proto.RegisterType((*QueryGetKycResponse)(nil), "mechain.mekyc.QueryGetKycResponse")
	proto.RegisterType((*QueryAllKycRequest)(nil), "mechain.mekyc.QueryAllKycRequest")
	proto.RegisterType((*QueryAllKycResponse)(nil), "mechain.mekyc.QueryAllKycResponse")
	proto.RegisterType((*QueryKycByRegionRequest)(nil), "mechain.mekyc.QueryKycByRegionRequest")
	proto.RegisterType((*QueryKycByRegionResponse)(nil), "mechain.mekyc.QueryKycByRegionResponse")
	proto.RegisterType((*QueryFixedDepositByRegionRequest)(nil), "mechain.mekyc.QueryFixedDepositByRegionRequest")
	proto.RegisterType((*QueryFixedDepositByRegionResponse)(nil), "mechain.mekyc.QueryFixedDepositByRegionResponse")
}

func init() { proto.RegisterFile("mechain/mekyc/query.proto", fileDescriptor_fe7261689e004517) }

var fileDescriptor_fe7261689e004517 = []byte{
	// 721 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0xe3, 0x06, 0x52, 0xba, 0x15, 0x97, 0xed, 0x57, 0x30, 0xe0, 0x36, 0x0b, 0xfd, 0xa0,
	0x12, 0x76, 0x3f, 0xe0, 0xc2, 0x2d, 0x15, 0x6a, 0x04, 0x11, 0x52, 0xc9, 0x11, 0x21, 0x45, 0x8e,
	0xbb, 0x18, 0xab, 0x8e, 0xd7, 0x8d, 0x5d, 0x54, 0xab, 0xaa, 0x84, 0x38, 0x70, 0xe0, 0x54, 0x09,
	0x89, 0x17, 0xe0, 0x19, 0x78, 0x87, 0x1e, 0x2b, 0x71, 0xe1, 0x84, 0x50, 0xcb, 0x83, 0x20, 0xef,
	0x8e, 0x9b, 0xd8, 0xde, 0x7c, 0x50, 0xf5, 0x50, 0xa9, 0xe9, 0xcc, 0xfc, 0xff, 0xbf, 0x99, 0xe9,
	0x8e, 0x82, 0xee, 0xb4, 0xa9, 0xf5, 0xde, 0x74, 0x3c, 0xa3, 0x4d, 0xf7, 0x22, 0xcb, 0xd8, 0x3f,
	0xa0, 0x9d, 0x48, 0xf7, 0x3b, 0x2c, 0x64, 0xf8, 0x36, 0x84, 0x74, 0x1e, 0x52, 0xa7, 0x6d, 0x66,
	0x33, 0x1e, 0x31, 0xe2, 0xdf, 0x44, 0x92, 0x7a, 0xcf, 0x66, 0xcc, 0x76, 0xa9, 0x61, 0xfa, 0x8e,
	0x61, 0x7a, 0x1e, 0x0b, 0xcd, 0xd0, 0x61, 0x5e, 0x00, 0xd1, 0x55, 0x8b, 0x05, 0x6d, 0x16, 0x18,
	0x2d, 0x33, 0xa0, 0x42, 0xdb, 0xf8, 0xb0, 0xde, 0xa2, 0xa1, 0xb9, 0x6e, 0xf8, 0xa6, 0xed, 0x78,
	0x3c, 0x19, 0x72, 0xd5, 0x34, 0x89, 0x6f, 0x76, 0xcc, 0x76, 0x20, 0x8f, 0x75, 0xa8, 0xdd, 0xad,
	0x9b, 0x4b, 0xc7, 0xf6, 0x22, 0x4b, 0x04, 0xc8, 0x34, 0xc2, 0xaf, 0x63, 0xcb, 0x1d, 0xae, 0xd4,
	0xa0, 0xfb, 0x07, 0x34, 0x08, 0xc9, 0x4b, 0x34, 0x95, 0xfa, 0x6b, 0xe0, 0x33, 0x2f, 0xa0, 0x78,
	0x13, 0x95, 0x84, 0x63, 0x59, 0x59, 0x50, 0x56, 0x26, 0x37, 0x66, 0xf4, 0x54, 0xf7, 0xba, 0x48,
	0xdf, 0xba, 0x71, 0xfa, 0x7b, 0xbe, 0xd0, 0x80, 0x54, 0xb2, 0x89, 0x66, 0xb8, 0x56, 0x8d, 0x86,
	0x0d, 0x8e, 0x04, 0x26, 0x58, 0x45, 0xb7, 0x04, 0xe3, 0x8b, 0x5d, 0xae, 0x37, 0xd1, 0xb8, 0xfc,
	0x4c, 0x5e, 0xa1, 0xd9, 0x6c, 0x51, 0x97, 0x41, 0x64, 0xf5, 0x61, 0x10, 0xe9, 0x09, 0x83, 0x48,
	0x25, 0x4d, 0x60, 0xa8, 0xba, 0x6e, 0x9a, 0x61, 0x1b, 0xa1, 0xee, 0x8c, 0x41, 0x71, 0x49, 0x17,
	0x0b, 0xd1, 0xe3, 0x85, 0xe8, 0x62, 0xd9, 0xb0, 0x10, 0x7d, 0xc7, 0xb4, 0x29, 0xd4, 0x36, 0x7a,
	0x2a, 0xc9, 0x37, 0x05, 0x80, 0x7b, 0x1c, 0x24, 0xc0, 0xc5, 0x11, 0x81, 0x71, 0x2d, 0xc5, 0x35,
	0xc6, 0xb9, 0x96, 0x87, 0x72, 0x09, 0xc7, 0x14, 0x98, 0x0e, 0xfb, 0xad, 0xd1, 0xb0, 0x1e, 0x59,
	0x49, 0xdb, 0x65, 0x34, 0x6e, 0x5a, 0x16, 0x3b, 0xf0, 0x42, 0x98, 0x7c, 0xf2, 0x91, 0x54, 0x61,
	0xf3, 0x49, 0x3e, 0x34, 0xb1, 0x8a, 0x8a, 0x7b, 0x91, 0x05, 0x03, 0xc2, 0x99, 0x0e, 0xea, 0x91,
	0x05, 0xf8, 0x71, 0x12, 0x79, 0x0b, 0x96, 0x55, 0xd7, 0xed, 0xb1, 0xbc, 0xae, 0x49, 0x7f, 0x51,
	0x80, 0x30, 0x91, 0xcf, 0x12, 0x16, 0x87, 0x12, 0x5e, 0xdf, 0x74, 0x9f, 0xa2, 0x39, 0xce, 0x12,
	0xeb, 0x47, 0xa3, 0xff, 0x77, 0xab, 0xa8, 0x9c, 0x2f, 0x13, 0xf2, 0xe4, 0xb3, 0x82, 0x16, 0x78,
	0x70, 0xdb, 0x39, 0xa4, 0xbb, 0xcf, 0xa9, 0xcf, 0x02, 0x27, 0xfc, 0x0f, 0xf1, 0xcc, 0xa0, 0xc7,
	0xae, 0x3c, 0x68, 0x17, 0x55, 0x06, 0x70, 0xc0, 0xd4, 0x6b, 0x92, 0xad, 0x5e, 0x65, 0x92, 0x1b,
	0xdf, 0xc7, 0xd1, 0x4d, 0x6e, 0x87, 0x19, 0x2a, 0x89, 0x3b, 0x82, 0x2b, 0x99, 0x2d, 0xe6, 0x0f,
	0x95, 0x4a, 0x06, 0xa5, 0xc0, 0x44, 0xb5, 0x4f, 0x3f, 0xff, 0x7e, 0x1d, 0x2b, 0xe3, 0x59, 0xa3,
	0x4d, 0x1f, 0xe7, 0xaf, 0x27, 0xfe, 0xa8, 0xa0, 0x92, 0x68, 0x0b, 0x3f, 0x94, 0xc9, 0x65, 0x0f,
	0x97, 0xba, 0x38, 0x24, 0x0b, 0x7c, 0x1f, 0x71, 0xdf, 0x07, 0xb8, 0x92, 0xf5, 0x15, 0xab, 0x32,
	0x8e, 0x92, 0x95, 0x1d, 0xe3, 0x43, 0x34, 0x21, 0x8a, 0xab, 0xae, 0x2b, 0x87, 0xc8, 0x5e, 0x2e,
	0x39, 0x44, 0xee, 0xfa, 0xf4, 0x6f, 0x1e, 0x0e, 0x4d, 0x80, 0x8a, 0xf5, 0xc8, 0x92, 0x8f, 0x3a,
	0x75, 0x33, 0xe4, 0xa3, 0x4e, 0x9f, 0x09, 0xb2, 0xc8, 0xdd, 0xe6, 0xf1, 0xfd, 0xac, 0x5b, 0xfc,
	0x73, 0x04, 0x37, 0xe6, 0x18, 0xbb, 0xa8, 0x54, 0x8f, 0xac, 0xb8, 0xd7, 0x4a, 0x9f, 0x2e, 0x86,
	0xf9, 0xa6, 0x1f, 0x3f, 0xb9, 0xcb, 0x7d, 0x67, 0xf0, 0x94, 0xc4, 0x17, 0x9f, 0x28, 0x68, 0xb2,
	0xe7, 0xa5, 0xe1, 0x25, 0x99, 0x60, 0xfe, 0x05, 0xab, 0xcb, 0x43, 0xf3, 0xc0, 0x7d, 0x8d, 0xbb,
	0xaf, 0xe2, 0x15, 0x89, 0x7b, 0xb3, 0x15, 0x35, 0xf3, 0xfb, 0xfe, 0xa1, 0xa0, 0x69, 0xd9, 0xbb,
	0xc2, 0x86, 0xcc, 0x73, 0xc0, 0x25, 0x50, 0xd7, 0x46, 0x2f, 0x00, 0xda, 0x67, 0x9c, 0xf6, 0x09,
	0xde, 0xc8, 0xd2, 0xbe, 0x8b, 0xab, 0x9a, 0xbb, 0xa2, 0x4c, 0xca, 0xbd, 0xb5, 0x76, 0x7a, 0xae,
	0x29, 0x67, 0xe7, 0x9a, 0xf2, 0xe7, 0x5c, 0x53, 0x4e, 0x2e, 0xb4, 0xc2, 0xd9, 0x85, 0x56, 0xf8,
	0x75, 0xa1, 0x15, 0xde, 0xcc, 0x5e, 0x8a, 0x1d, 0x82, 0x5c, 0x18, 0xf9, 0x34, 0x68, 0x95, 0xf8,
	0xd7, 0x8c, 0xcd, 0x7f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa1, 0xce, 0x22, 0x4c, 0x43, 0x09, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of Region items.
	Region(ctx context.Context, in *QueryGetRegionRequest, opts ...grpc.CallOption) (*QueryGetRegionResponse, error)
	RegionAll(ctx context.Context, in *QueryAllRegionRequest, opts ...grpc.CallOption) (*QueryAllRegionResponse, error)
	// Queries a list of Kyc items.
	Kyc(ctx context.Context, in *QueryGetKycRequest, opts ...grpc.CallOption) (*QueryGetKycResponse, error)
	KycAll(ctx context.Context, in *QueryAllKycRequest, opts ...grpc.CallOption) (*QueryAllKycResponse, error)
	// Queries a list of KycByRegion items.
	KycByRegion(ctx context.Context, in *QueryKycByRegionRequest, opts ...grpc.CallOption) (*QueryKycByRegionResponse, error)
	// Queries a list of FixedDepositByRegion items.
	FixedDepositByRegion(ctx context.Context, in *QueryFixedDepositByRegionRequest, opts ...grpc.CallOption) (*QueryFixedDepositByRegionResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Region(ctx context.Context, in *QueryGetRegionRequest, opts ...grpc.CallOption) (*QueryGetRegionResponse, error) {
	out := new(QueryGetRegionResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/Region", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RegionAll(ctx context.Context, in *QueryAllRegionRequest, opts ...grpc.CallOption) (*QueryAllRegionResponse, error) {
	out := new(QueryAllRegionResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/RegionAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Kyc(ctx context.Context, in *QueryGetKycRequest, opts ...grpc.CallOption) (*QueryGetKycResponse, error) {
	out := new(QueryGetKycResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/Kyc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KycAll(ctx context.Context, in *QueryAllKycRequest, opts ...grpc.CallOption) (*QueryAllKycResponse, error) {
	out := new(QueryAllKycResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/KycAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) KycByRegion(ctx context.Context, in *QueryKycByRegionRequest, opts ...grpc.CallOption) (*QueryKycByRegionResponse, error) {
	out := new(QueryKycByRegionResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/KycByRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) FixedDepositByRegion(ctx context.Context, in *QueryFixedDepositByRegionRequest, opts ...grpc.CallOption) (*QueryFixedDepositByRegionResponse, error) {
	out := new(QueryFixedDepositByRegionResponse)
	err := c.cc.Invoke(ctx, "/mechain.mekyc.Query/FixedDepositByRegion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of Region items.
	Region(context.Context, *QueryGetRegionRequest) (*QueryGetRegionResponse, error)
	RegionAll(context.Context, *QueryAllRegionRequest) (*QueryAllRegionResponse, error)
	// Queries a list of Kyc items.
	Kyc(context.Context, *QueryGetKycRequest) (*QueryGetKycResponse, error)
	KycAll(context.Context, *QueryAllKycRequest) (*QueryAllKycResponse, error)
	// Queries a list of KycByRegion items.
	KycByRegion(context.Context, *QueryKycByRegionRequest) (*QueryKycByRegionResponse, error)
	// Queries a list of FixedDepositByRegion items.
	FixedDepositByRegion(context.Context, *QueryFixedDepositByRegionRequest) (*QueryFixedDepositByRegionResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) Region(ctx context.Context, req *QueryGetRegionRequest) (*QueryGetRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Region not implemented")
}
func (*UnimplementedQueryServer) RegionAll(ctx context.Context, req *QueryAllRegionRequest) (*QueryAllRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegionAll not implemented")
}
func (*UnimplementedQueryServer) Kyc(ctx context.Context, req *QueryGetKycRequest) (*QueryGetKycResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Kyc not implemented")
}
func (*UnimplementedQueryServer) KycAll(ctx context.Context, req *QueryAllKycRequest) (*QueryAllKycResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KycAll not implemented")
}
func (*UnimplementedQueryServer) KycByRegion(ctx context.Context, req *QueryKycByRegionRequest) (*QueryKycByRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method KycByRegion not implemented")
}
func (*UnimplementedQueryServer) FixedDepositByRegion(ctx context.Context, req *QueryFixedDepositByRegionRequest) (*QueryFixedDepositByRegionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FixedDepositByRegion not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Region_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Region(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/Region",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Region(ctx, req.(*QueryGetRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RegionAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RegionAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/RegionAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RegionAll(ctx, req.(*QueryAllRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Kyc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetKycRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Kyc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/Kyc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Kyc(ctx, req.(*QueryGetKycRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KycAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllKycRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KycAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/KycAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KycAll(ctx, req.(*QueryAllKycRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_KycByRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryKycByRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).KycByRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/KycByRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).KycByRegion(ctx, req.(*QueryKycByRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_FixedDepositByRegion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFixedDepositByRegionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).FixedDepositByRegion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mechain.mekyc.Query/FixedDepositByRegion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).FixedDepositByRegion(ctx, req.(*QueryFixedDepositByRegionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "mechain.mekyc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "Region",
			Handler:    _Query_Region_Handler,
		},
		{
			MethodName: "RegionAll",
			Handler:    _Query_RegionAll_Handler,
		},
		{
			MethodName: "Kyc",
			Handler:    _Query_Kyc_Handler,
		},
		{
			MethodName: "KycAll",
			Handler:    _Query_KycAll_Handler,
		},
		{
			MethodName: "KycByRegion",
			Handler:    _Query_KycByRegion_Handler,
		},
		{
			MethodName: "FixedDepositByRegion",
			Handler:    _Query_FixedDepositByRegion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mechain/mekyc/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetRegionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRegionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRegionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRegionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRegionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRegionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Region.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllRegionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRegionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRegionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRegionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Region) > 0 {
		for iNdEx := len(m.Region) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Region[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKycRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKycRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKycRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Account) > 0 {
		i -= len(m.Account)
		copy(dAtA[i:], m.Account)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Account)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetKycResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetKycResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetKycResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Kyc.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllKycRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKycRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKycRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllKycResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllKycResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllKycResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Kyc) > 0 {
		for iNdEx := len(m.Kyc) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Kyc[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryKycByRegionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryKycByRegionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryKycByRegionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryKycByRegionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryKycByRegionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryKycByRegionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryFixedDepositByRegionRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFixedDepositByRegionRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFixedDepositByRegionRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.RegionId) > 0 {
		i -= len(m.RegionId)
		copy(dAtA[i:], m.RegionId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.RegionId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFixedDepositByRegionResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFixedDepositByRegionResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFixedDepositByRegionResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetRegionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRegionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Region.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllRegionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRegionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Region) > 0 {
		for _, e := range m.Region {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKycRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Account)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetKycResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Kyc.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllKycRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllKycResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Kyc) > 0 {
		for _, e := range m.Kyc {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryKycByRegionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryKycByRegionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryFixedDepositByRegionRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.RegionId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFixedDepositByRegionResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRegionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRegionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRegionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRegionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRegionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRegionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Region.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRegionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRegionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRegionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Region", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Region = append(m.Region, Region{})
			if err := m.Region[len(m.Region)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKycRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKycRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKycRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Account", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Account = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetKycResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetKycResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetKycResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kyc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Kyc.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKycRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKycRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKycRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllKycResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllKycResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllKycResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Kyc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Kyc = append(m.Kyc, Kyc{})
			if err := m.Kyc[len(m.Kyc)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryKycByRegionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryKycByRegionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryKycByRegionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryKycByRegionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryKycByRegionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryKycByRegionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFixedDepositByRegionRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFixedDepositByRegionRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFixedDepositByRegionRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RegionId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RegionId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFixedDepositByRegionResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFixedDepositByRegionResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFixedDepositByRegionResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
