name: build-me-chain

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    name: build-me-chain

    runs-on: self-hosted

    steps:
      - name: Checkout me-chain
        uses: actions/checkout@main

      - name: go mod tidy
        run: |
          go mod tidy

      - name: build
        run: |
          make clean && make build

      - name: archive
        run: |
          pwd
          cp build/me-chaind /data/ssd2/archive/me/latest/